### ISSUE TITLE
npm start not working for webpack-dev-server

### ISSUE THREAD

**Issue by poonam125sharma** [wbkd/webpack-starter#80]
After cloning this repo and doing `npm install`. When I did `npm start`. My webpack-dev-server does not start, instead, it gives the below error. What could be the issue for this error?

webpack-starter@1.0.0 start D:\D-Drive\WebDevelopment\JavaScript\Pluralsight\JavaScript-Fundamentals\webpack-starter
> webpack-dev-server --open --config webpack/webpack.config.dev.js

i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from D:\D-Drive\WebDevelopment\JavaScript\Pluralsight\JavaScript-Fundamentals\webpack-starter
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack-starter@1.0.0 start: `webpack-dev-server --open --config webpack/webpack.config.dev.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-starter@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by g-div** [comment]
In your case Webpack can't find a specific file (cannot see which one). It seems to be a problem of webpack, probably related to windows environments.
Unfortunately I can't help you, since I don't use windows and I've never experienced the error before.

You can eventually try to debug the `webpack/webpack.config.dev.js` file in order to find out if the problem concerns the configuration. In any case I would recommend to refer to the [webpack](https://webpack.js.org/)/[webpack-dev-server](https://github.com/webpack/webpack-dev-server) documentation/community, since I'm sure you will find help about your specific case there.

I will close this issue for now. Please reopen it if you can provide further details about an eventual configuration error.
